name: vendorapp_mulitvendorapp
description: Vendor App of Multivendor app project


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  image_picker: ^0.6.7+17
  provider: ^4.3.2+3
  location: ^3.2.1
  geocoder: ^0.2.1
  email_validator: ^1.0.5
  firebase_storage: ^5.2.0
  flutter_slider_drawer: ^1.2.1
  flutter_easyloading: ^2.2.2






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
